# Generated by Django 5.2.8 on 2026-02-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='dark'),
        ),
    ]
