# Generated by Django 5.2.8 on 2026-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications_enabled',
            field=models.BooleanField(default=False, verbose_name='Уведомления на Email'),
        ),
    ]
