# Generated by Django 5.2.8 on 2026-03-09 09:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verified',
            field=models.BooleanField(default=False, verbose_name='Номер телефона подтверждён'),
        ),
    ]
