# Generated by Django 5.2.8 on 2026-05-14 06:59

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0006_remove_sellerrating_is_positive_sellerrating_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.DurationField(verbose_name='Срок действия')),
                ('can_be_combined', models.BooleanField(default=True, verbose_name='Можно комбинировать с другими услугами')),
                ('is_exclusive', models.BooleanField(default=False, help_text='Может быть активна только на одном объявлении во всей системе в один момент времени', verbose_name='Эксклюзивная услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'promo',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Оценка')),
                ('status', models.CharField(choices=[('rejected', 'отклонён'), ('published', 'опубликован')], default='published', max_length=9, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='promo.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв об услуге',
                'verbose_name_plural': 'Отзывы об услугах',
                'db_table': 'paid_service_reviews',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Слаг')),
                ('services', models.ManyToManyField(related_name='types', to='promo.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
                'db_table': 'paid_service_types',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('unread', 'Не прочитано'), ('pending', 'В ожидании'), ('cancelled', 'Отменено'), ('completed', 'Выполнено')], default='unread', max_length=9, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='ads.advertisement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.service', verbose_name='Услуга')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'paid_service_requests',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ever_used', models.BooleanField(default=False, verbose_name='Хоть раз была использована')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_services', to='ads.advertisement', verbose_name='Продвигаемое объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='promo.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'db_table': 'paid_service_purchases',
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service_purchase')],
            },
        ),
    ]
