# Generated by Django 5.2.8 on 2026-02-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP статус (значок)')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно (огонек)')),
                ('is_colored', models.BooleanField(default=False, verbose_name='Выделение цветом (рамка)')),
                ('is_top', models.BooleanField(default=False, verbose_name='Поднято в топ')),
                ('vip_paid', models.BooleanField(default=False, verbose_name='VIP оплачен')),
                ('top_paid', models.BooleanField(default=False, verbose_name='Топ оплачен')),
                ('colored_paid', models.BooleanField(default=False, verbose_name='Рамка оплачена')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='ads.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Продвижение объявления',
                'verbose_name_plural': 'Продвижение объявлений',
            },
        ),
    ]
