# Generated by Django 5.2.8 on 2026-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpromotion',
            name='urgent_paid',
            field=models.BooleanField(default=False, verbose_name='Топ оплачен'),
        ),
    ]
