# Generated by Django 5.2.8 on 2026-05-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adpromotion_urgent_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('under_review', 'На проверке'), ('rejected', 'Отклонено')], db_index=True, default='under_review', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
