# Generated by Django 5.2.8 on 2026-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerrating',
            name='is_positive',
        ),
        migrations.AddField(
            model_name='sellerrating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
            preserve_default=False,
        ),
    ]
