# Generated by Django 5.2.8 on 2026-06-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_sellerrating_is_positive_sellerrating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpromotion',
            name='colored_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Рамка действует до'),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='top_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Топ действует до'),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='urgent_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срочно действует до'),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='vip_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP действует до'),
        ),
    ]
